### ISSUE TITLE
Upgrade `scalaz` to 7.2.2

### ISSUE THREAD

**Issue by Primetalk** [cotiviti/cotiviti-parent#35]
We've got a dependency hell in `cpl-web` because of the conflict `scalaz` `7.1.7` and `7.2.x` (required by `scalatra-specs`).

There is an `argonaut:6.1a` that resolves the problem completely.

**Comment by isomarcte** [comment]
This is fixed in https://github.com/cotiviti/cotiviti-parent/pull/36
